# -*- coding: utf-8 -*-
from setuptools import setup

packages = ["aksdp", "aksdp.data", "aksdp.dataset", "aksdp.graph", "aksdp.repository", "aksdp.task", "aksdp.util"]

package_data = {"": ["*"]}

install_requires = ["boto3>=1.13.25,<2.0.0", "pandas>=1.0.4,<2.0.0", "sqlalchemy>=1.3.17,<2.0.0"]

setup_kwargs = {
    "name": "aksdp",
    "version": "0.1.0",
    "description": "Simple DataPipelene framework",
    "long_description": None,
    "author": "Y.Arimitsu",
    "author_email": "yoshikazu_arimitsu@albert2005.co.jp",
    "maintainer": None,
    "maintainer_email": None,
    "url": "https://github.com/YoshikazuArimitsu/aksdp",
    "packages": packages,
    "package_data": package_data,
    "install_requires": install_requires,
    "python_requires": ">=3.6.1,<4.0.0",
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
